version: '2'

services:
  backend:
    build: .
    ports:
      - 8002:8000
      - 9230:9229 # debugger port
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: yarn start:docker
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgres://postgres@postgres/blog_app
      PORT: 8002

  postgres:
    image: postgres:14-alpine
    ports:
      - 5444:5432
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: blog_app